name: Build and tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [20]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Enable corepack
        run: npm i -fg corepack && corepack enable

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint

      - name: Test project
        run: pnpm test

      - name: Build project
        run: pnpm build

      - name: Cache dist
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-${{ github.sha }}

  nightly-release:
    needs:
      - test
    strategy:
      matrix:
        node: [20]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: npm i -fg corepack && corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore dist cache
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-${{ github.sha }}

      - name: Release Nightly
        if: |
          github.event_name == 'push' &&
          !startsWith(github.event.head_commit.message, '[skip-release]') &&
          !startsWith(github.event.head_commit.message, 'chore') &&
          !startsWith(github.event.head_commit.message, 'docs')
        run: ./scripts/release-nightly.sh
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
