name: Build playgrounds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Enable corepack
        run: npm i -fg corepack && corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project (Vite)
        run: pnpm build:vite

      - name: Build project (Nuxt)
        run: pnpm build:nuxt

      - name: Build project (Vite SSG)
        run: pnpm build:ssg
